#!/bin/sh
a="-Pro"
css="layout.css grid.css dark.css vditor-render.css comment.css animate.min.css callback.css ks.css hint.css"
js="component-native.min.js headroom.js polyfill.min.js devtools-detector.js"
echo "STY 打包程序"
echo "打包版本号"
read a
cd /Users/wibus/Desktop/wibus/Wibus\ blog/Develop-Typecho

# mkdir STY
echo "copy STY(in safe mode)"
cp -rf STY ~/desktop/STY
cd ~/desktop/STY

echo "delete .git & workflows"
trash .git
trash .github

# delete themes's git
cd ~/desktop/STY/themes
cd icarus
trash .git
cd ..

echo "create getAuth.php"
trash ~/desktop/STY/system/Interface/getAuth.php
cp -rf /Users/wibus/Desktop/wibus/Wibus\ blog/Develop-Typecho/sty-tmp/getAuth.php ~/desktop/STY/system/Interface/getAuth.php


echo "Replace version"
cd ~/desktop/STY
fileContent=`cd ~/desktop/STY && cat index.php`
# echo $fileContent
echo ${fileContent/@version/@version $a} > index.php

echo "Compressing STY"
cd ~/desktop
zip -q -r -P Wibus STY\ v$a.zip STY

echo "Delete dir(in safe mode)"
trash STY